import { Product, Review } from "@/types/product";

// Demo product data — clearly labelled as mock/demo content
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "leopard-pendant-set",
    name: "Leopard Pendant Set",
    description: "A regal leopard pendant necklace crafted in antique gold finish.",
    longDescription: "Inspired by the graceful and powerful leopard, this pendant set brings wild elegance to your everyday look. The intricate detailing captures the spirit of the big cat, making it a conversation piece that connects fashion with nature. Perfect for the nature lover who appreciates artisan craftsmanship.",
    price: 1899,
    originalPrice: 2499,
    images: [
      "/images/products/leopard_pendant.png",
      "/images/products/peacock_necklace.png",
    ],
    category: "Necklace",
    collection: "WWJ Jewellery",
    animalInspiration: "Leopard",
    material: "Antique Gold Plated Alloy",
    colors: ["Gold", "Antique Gold"],
    inStock: true,
    stockCount: 15,
    sku: "WWJ-NKS-001",
    isBestseller: true,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 128,
    features: ["Handcrafted", "Adjustable chain", "Nickel-free", "Lead-free"],
    careInstructions: "Store in a cool, dry place. Avoid contact with water and perfumes. Clean with a soft cloth.",
    tags: ["leopard", "necklace", "gold", "wildlife", "bestseller"],
  },
  {
    id: "2",
    slug: "owl-wisdom-ring",
    name: "Owl Wisdom Ring",
    description: "A delicate owl-motif ring symbolising wisdom and mystery.",
    longDescription: "The owl has long been associated with wisdom, intuition, and the magic of the night. This ring captures the owl's intricate feather detail in antique gold, making it a meaningful piece for those who value both style and symbolism.",
    price: 999,
    images: [
      "/images/products/owl_ring.png",
    ],
    category: "Rings",
    collection: "WWJ Jewellery",
    animalInspiration: "Owl",
    material: "Antique Gold Plated Brass",
    colors: ["Gold"],
    inStock: true,
    stockCount: 30,
    sku: "WWJ-RNG-002",
    isBestseller: false,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 96,
    features: ["Handcrafted", "Adjustable size", "Nickel-free"],
    careInstructions: "Store in a cool, dry place. Avoid contact with water and perfumes.",
    tags: ["owl", "ring", "wisdom", "wildlife", "new arrival"],
  },
  {
    id: "3",
    slug: "butterfly-wing-earrings",
    name: "Butterfly Wing Earrings",
    description: "Delicate butterfly wing earrings in a vibrant enamel finish.",
    longDescription: "Inspired by the ephemeral beauty of butterflies, these earrings feature hand-painted enamel wings in jewel tones. Each pair is unique, just like the wings they're inspired by. Lightweight and comfortable for all-day wear.",
    price: 1299,
    originalPrice: 1599,
    images: [
      "/images/products/butterfly_earrings.png",
    ],
    category: "Earrings",
    collection: "WWJ Jewellery",
    animalInspiration: "Butterfly",
    material: "Gold Plated with Enamel",
    colors: ["Multi-color", "Gold"],
    inStock: true,
    stockCount: 22,
    sku: "WWJ-EAR-003",
    isBestseller: false,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 74,
    features: ["Handcrafted", "Enamel painted", "Lightweight", "Push back closure"],
    careInstructions: "Avoid contact with water. Do not rub the enamel. Store separately to prevent scratching.",
    tags: ["butterfly", "earrings", "enamel", "colorful", "wildlife"],
  },
  {
    id: "4",
    slug: "deer-antler-necklace",
    name: "Deer Antler Necklace",
    description: "An elegant deer-inspired layered necklace with delicate antler detail.",
    longDescription: "The deer symbolises grace, sensitivity, and gentle strength. This layered necklace features a beautifully detailed antler pendant on a fine gold chain. Pair it with your favourite outfit to bring a touch of the forest into your daily style.",
    price: 1599,
    images: [
      "/images/products/deer_necklace.png",
    ],
    category: "Necklace",
    collection: "WWJ Jewellery",
    animalInspiration: "Deer",
    material: "Gold Plated Brass",
    colors: ["Gold"],
    inStock: true,
    stockCount: 18,
    sku: "WWJ-NKS-004",
    isBestseller: false,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 118,
    features: ["Handcrafted", "Layered chain", "Adjustable length"],
    careInstructions: "Store in a cool, dry place. Avoid contact with water and perfumes.",
    tags: ["deer", "necklace", "layered", "wildlife", "elegant"],
  },
  {
    id: "5",
    slug: "panda-charm-keychain",
    name: "Panda Charm Keychain",
    description: "A cute handcrafted panda charm keychain — the perfect wildlife gift.",
    longDescription: "Celebrate the beloved giant panda with this adorable handcrafted charm keychain. Made with attention to detail, this keychain is a small daily reminder of the beautiful wildlife that surrounds us. Also makes for a thoughtful gift.",
    price: 499,
    images: [
      "/images/products/panda_keychain.png",
    ],
    category: "Keychains",
    collection: "WWA Accessories",
    animalInspiration: "Panda",
    material: "Resin and Alloy",
    colors: ["Black & White"],
    inStock: true,
    stockCount: 50,
    sku: "WWA-KEY-005",
    isBestseller: false,
    isNewArrival: false,
    rating: 4.8,
    reviewCount: 45,
    features: ["Handcrafted", "Durable resin", "Metal key ring included"],
    careInstructions: "Wipe clean with a dry cloth. Avoid prolonged exposure to sunlight.",
    tags: ["panda", "keychain", "gift", "accessories", "cute"],
  },
  {
    id: "6",
    slug: "peacock-feather-bracelet",
    name: "Peacock Feather Bracelet",
    description: "A stunning peacock-feather-inspired bangle in teal and gold enamel.",
    longDescription: "The peacock is the ultimate symbol of beauty, confidence, and grace. This bangle captures that energy with its hand-painted teal and gold enamel feather design. Worn alone or stacked, it makes an unforgettable statement.",
    price: 1199,
    originalPrice: 1499,
    images: [
      "/images/products/peacock_necklace.png",
    ],
    category: "Bracelets",
    collection: "WWJ Jewellery",
    animalInspiration: "Peacock",
    material: "Gold Plated Brass with Enamel",
    colors: ["Teal", "Gold"],
    inStock: true,
    stockCount: 25,
    sku: "WWJ-BRC-006",
    isBestseller: true,
    isNewArrival: false,
    rating: 4.7,
    reviewCount: 89,
    features: ["Handcrafted", "Enamel painted", "Comfortable fit", "Adjustable"],
    careInstructions: "Store separately to prevent scratching the enamel. Avoid water contact.",
    tags: ["peacock", "bracelet", "enamel", "teal", "wildlife", "bestseller"],
  },
  {
    id: "7",
    slug: "tiger-stripe-hair-clip",
    name: "Tiger Stripe Hair Clip",
    description: "Bold tiger-stripe patterned hair clip in gold and black enamel.",
    longDescription: "Inspired by the majestic Bengal tiger, this hair clip brings fierce yet refined style to any look. The bold stripe pattern in black and gold enamel is perfect for those who want to make a statement.",
    price: 799,
    images: [
      "/images/wildlife/deer.png",
    ],
    category: "Hair Accessories",
    collection: "WWJ Jewellery",
    animalInspiration: "Tiger",
    material: "Acetate with Gold Hardware",
    colors: ["Black", "Gold"],
    inStock: true,
    stockCount: 35,
    sku: "WWJ-HAR-007",
    isBestseller: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 42,
    features: ["Handcrafted", "Secure grip", "Comfortable for all-day wear"],
    careInstructions: "Wipe clean with a dry cloth. Store in a pouch to prevent scratches.",
    tags: ["tiger", "hair clip", "bold", "wildlife", "new arrival"],
  },
  {
    id: "8",
    slug: "elephant-family-gift-box",
    name: "Elephant Family Gift Box",
    description: "A curated gift set of elephant-inspired jewellery pieces in a beautiful box.",
    longDescription: "The elephant represents family, loyalty, and wisdom. This curated gift box includes a pendant necklace, a matching bracelet, and earrings — all inspired by the gentle giant. Beautifully packaged in a WWJ gift box, ready to gift.",
    price: 2999,
    originalPrice: 3999,
    images: [
      "/images/collections/gifting_box.png",
      "/images/products/elephant_keychain.png",
    ],
    category: "Gift Boxes",
    collection: "Gifting Collection",
    animalInspiration: "Elephant",
    material: "Gold Plated Alloy with Enamel",
    colors: ["Gold", "Ivory"],
    inStock: true,
    stockCount: 10,
    sku: "GFT-BOX-008",
    isBestseller: false,
    isNewArrival: false,
    rating: 5.0,
    reviewCount: 33,
    features: ["3-piece set", "Ready-to-gift packaging", "Handcrafted", "Customisable card available"],
    careInstructions: "Individual care instructions included inside the box.",
    tags: ["elephant", "gift box", "set", "family", "gifting"],
  },
];

// Demo reviews — clearly labelled as demo content
export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    productId: "1",
    author: "Priya S.",
    rating: 5,
    title: "Absolutely love it!",
    body: "The leopard pendant is stunning. The craftsmanship is so detailed and the gold finish looks very premium. Received many compliments. Will definitely order again!",
    date: "2024-11-15",
    verified: true,
  },
  {
    id: "r2",
    productId: "3",
    author: "Ananya M.",
    rating: 5,
    title: "Perfect for gifting!",
    body: "Bought these butterfly earrings as a birthday gift for my best friend. She absolutely loved them! The packaging was beautiful and the earrings are so light and comfortable.",
    date: "2024-12-03",
    verified: true,
  },
  {
    id: "r3",
    productId: "6",
    author: "Divya K.",
    rating: 4,
    title: "Beautiful bracelet",
    body: "The peacock bracelet is gorgeous. The colours are vibrant and the enamel work is very well done. Only giving 4 stars because the clasp is a bit tricky. Otherwise, highly recommend!",
    date: "2025-01-08",
    verified: true,
  },
];

export const PRODUCT_CATEGORIES = [
  "All",
  "Necklace",
  "Combo",
  "Sets",
  "Rings",
  "Earrings",
  "Bracelets",
  "Hair Accessories",
  "Keychains",
  "Gift Boxes",
  "Magnets",
  "Festive Collections",
];

export const ANIMAL_INSPIRATIONS = [
  "All",
  "Leopard",
  "Owl",
  "Butterfly",
  "Deer",
  "Panda",
  "Peacock",
  "Tiger",
  "Elephant",
];

export const COLLECTIONS_LIST = [
  { slug: "jewellery", name: "WWJ Jewellery", description: "Handcrafted animal-inspired fashion pieces." },
  { slug: "accessories", name: "WWA Accessories", description: "Cute everyday wildlife collectibles." },
  { slug: "gifting", name: "Gifting Collection", description: "Ready-to-gift pieces & curated sets." },
];
